networks:
  shared_network:
    driver: bridge

services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    # deploy:
      # resources:
        # reservations:
          # devices:
            # - driver: gpu
              # capabilities: [compute, utility]
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    ports:
      - "8080:8080"
    networks:
      - shared_network
    volumes:
      - openwebui-data:/usr/src/app/models
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: unless-stopped

  bolt-diy:
    image: ghcr.io/thecodacus/dash-ai:6d94bef
    pull_policy: always
    container_name: bolt-diy
    env_file: ".env.local"
    ports:
      - "3000:5173" 
    networks:
      - shared_network
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      # No strictly needed but serving as hints for Coolify
      - PORT=5173
      #- OLLAMA_API_BASE_URL=http://host.docker.internal:11434
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    restart: unless-stopped

volumes:
  ollama:
  openwebui-data:
  bolt-diy-data:
