networks:
  shared_network:
    driver: bridge

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11434:11434"  # Maps Ollama service port to host
    runtime: nvidia
    networks:
      - shared_network  # Connects to the shared network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=0.0.0.0:11434  # Ensures binding to all network interfaces
      - OLLAMA_DEBUG=true
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "8080:8080"  # Maps OpenWebUI default port to host
    runtime: nvidia
    networks:
      - shared_network  # Connects to the shared network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_URL=http://ollama:11434  # Ensures OpenWebUI connects to Ollama
    volumes:
      - openwebui-data:/usr/src/app/models  # Persistent model storage
    restart: unless-stopped

volumes:
  openwebui-data:
