networks:
  shared_network:
    driver: bridge

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"  # Maps Ollama service port to host
    runtime: nvidia
    networks:
      - shared_network  # Connects to the shared network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=0.0.0.0:11434  # Ensures binding to all network interfaces
      - OLLAMA_DEBUG=true
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    ports:
      - "8080:8080"  # Maps OpenWebUI default port to host
    runtime: nvidia
    networks:
      - shared_network  # Connects to the shared network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_URL=http://host.docker.internal:11434  # Ensures OpenWebUI connects to Ollama
    volumes:
      - openwebui-data:/usr/src/app/models  # Persistent model storage
    restart: unless-stopped

  bolt-diy-stable:
    image: ghcr.io/stackblitz-labs/bolt.diy:stable
    container_name: bolt-diy-stable
    env_file: ".env.local"
    ports:
      - "3000:5173"
    networks:
      - shared_network
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    volumes:
      - bolt-diy-data:/usr/src/app/data # Persistent storage for Bolt DIY
    restart: unless-stopped
    profiles:
      - stable

  bolt-diy-latest:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    container_name: bolt-diy-latest
    env_file: ".env.local"
    ports:
      - "3000:5173"
    networks:
      - shared_network
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    volumes:
      - bolt-diy-data:/usr/src/app/data # Persistent storage for Bolt DIY
    restart: unless-stopped
    profiles:
      - latest

volumes:
  ollama:
  openwebui-data:
  bolt-diy-data:
