networks:
  shared_network:
    driver: bridge

services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    ports:
      - "8080:8080"
    networks:
      - shared_network
    volumes:
      - openwebui-data:/usr/src/app/models
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: unless-stopped

  bolt-diy-stable:
    image: ghcr.io/stackblitz-labs/bolt.diy:stable
    container_name: bolt-diy-stable
    env_file: ".env.local"
    ports:
      - "3000:5173"
    networks:
      - shared_network
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    volumes:
      - bolt-diy-data:/usr/src/app/data
    restart: unless-stopped
    profiles:
      - stable

  bolt-diy-latest:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    container_name: bolt-diy-latest
    env_file: ".env.local"
    ports:
      - "3000:5173"
    networks:
      - shared_network
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    volumes:
      - bolt-diy-data:/usr/src/app/data
    restart: unless-stopped
    profiles:
      - latest

volumes:
  ollama:
  openwebui-data:
  bolt-diy-data:
